# Generated by Django 2.2.7 on 2019-11-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photo/%y/%m/%d/')),
                ('username', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
