# Generated by Django 2.2.7 on 2019-11-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_album_list_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='username',
        ),
    ]
